### ISSUE TITLE
Required grelimpython package is removed from pipfile/requirements

### ISSUE THREAD

**Issue by harshad16** [thoth-station/lab#129]
**Describe the bug**
grelimpython package is removed from Pipfile and requirements.txt, but it is required and used by thoth/lab/graph.py .
https://github.com/thoth-station/lab/blob/dfe929a6fadd05f92e3140573cc53820ae59dc35/thoth/lab/graph.py#L28
Installing and using thoth-lab in any other module causes No module error for grelimpython.

**Comment by fridex** [comment]
Nice catch! thoth-lab seems to be not fully ported to dgraph. We should probably also refactor manipulation with query results and their projection to dataframes.

**Comment by fridex** [comment]
Closing this as it is no longer relevant.
