### ISSUE TITLE
PR are not merged automatically when reviewer approved them and checks are finished successfully

### ISSUE THREAD

**Issue by pacospace** [thoth-station/lab#168]

**Comment by harshad16** [comment]
Hey @pacospace  :smile: ,
which PR observed this behavior? can you please add the link of PR here it would be helpful.

**Comment by pacospace** [comment]
> Hey @pacospace  ,
> which PR observed this behavior? can you please add the link of PR here it would be helpful.

Actually it was merged now :/ I'll close issue for now, if I spot it again I will let you know :)
